-- activiti5.6 history
CALL DROP_USER_TABLE('ACT_HI_PROCINST');
CALL DROP_USER_TABLE('ACT_HI_ACTINST');
CALL DROP_USER_TABLE('ACT_HI_TASKINST');
CALL DROP_USER_TABLE('ACT_HI_DETAIL');
CALL DROP_USER_TABLE('ACT_HI_COMMENT');
CALL DROP_USER_TABLE('ACT_HI_ATTACHMENT');
