-- activiti5.6 engine
CALL DROP_USER_TABLE('ACT_GE_PROPERTY');
CALL DROP_USER_TABLE('ACT_RU_VARIABLE');
CALL DROP_USER_TABLE('ACT_RU_JOB');
CALL DROP_USER_TABLE('ACT_GE_BYTEARRAY');
CALL DROP_USER_TABLE('ACT_RE_DEPLOYMENT');
CALL DROP_USER_TABLE('ACT_RU_IDENTITYLINK');
CALL DROP_USER_TABLE('ACT_RU_TASK');
CALL DROP_USER_TABLE('ACT_RE_PROCDEF');
CALL DROP_USER_TABLE('ACT_RU_EXECUTION');
