-- activiti5.6 cycle
CALL DROP_USER_TABLE('ACT_CY_CONN_CONFIG');
CALL DROP_USER_TABLE('ACT_CY_CONFIG');
CALL DROP_USER_TABLE('ACT_CY_LINK');
CALL DROP_USER_TABLE('ACT_CY_PEOPLE_LINK');
CALL DROP_USER_TABLE('ACT_CY_TAG');
CALL DROP_USER_TABLE('ACT_CY_COMMENT');
CALL DROP_USER_TABLE('ACT_CY_V_FOLDER');
CALL DROP_USER_TABLE('ACT_CY_PROCESS_SOLUTION');
